#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Bank Reconciling Tool', 'v1.0.0');

$application->add(new \Edcs\Reconciler\Commands\Reconcile());

try {
    $application->run();
} catch (Exception $ex) {
    exit(1);
}
